### ISSUE TITLE
Required error

### ISSUE THREAD

**Issue by EchoPouet** [madprops/nap#2]
Hello,

I found an issue with the "required" option. My example is (created from your readme):
```
import nap

let bar = use_arg(name="bar", kind="value", required=false, help="Heaps Alloy", alt="b")

parse_args()

if bar.used:
    echo bar.value
```
and the result is:
```
./tests/test -b
'--bar' needs a value.
```
In your description, the "required" option allows to call this option without passing value.

I fix this issue after adding "value" parameter to given default value.

`let bar = use_arg(name="bar", kind="value", required=false, value="cosmic", help="Heaps Alloy", alt="b")`

A compilation error should appear in this case to prevent this problem.

Thanks.

**Comment by madprops** [comment]
Hi. 'required' means it's not required for the user to provide '--bar' or '-b' at all. If the user does provide it, it will check if a value was provided since it's of kind 'value', and throw an error if not. I could disable the value checking on required=false but it would be weird if the user did try to use the 'bar' argument but used it wrong.

**Comment by EchoPouet** [comment]
`If the user does provide it, it will check if a value was provided since it's of kind 'value', and throw an error if not.`

Ok but can you explain this in the readme for others users plz.

Thanks.
