### ISSUE TITLE
Robust value kind name

### ISSUE THREAD

**Issue by EchoPouet** [madprops/nap#3]
Hello,

I tested this code:
```
import nap

let bar = use_arg(name="bar", kind="value", required=false, value="cosmic", help="Heaps Alloy", alt="b")

parse_args()

if bar.used:
    echo bar.value
```
And I found these results:
```
$ ./tests/test --ba
cosmic
$ ./tests/test --bar
cosmic
$ ./tests/test --ba=lol
lol
```

It's normal ?

**Comment by madprops** [comment]
Yes. The first two use the value provided to 'bar' (value="cosmic"). 
As for why '--ba' works: https://github.com/madprops/nap/issues/1
The last line sets the value of 'bar' to 'lol'.
As for why the first two don't throw an error, it's because internally they already have a value (cosmic) so it doesn't fail when checked. Though I admit this is kind of confusing since the flags are being used incorrectly.
